### PR TITLE
Remove Prefix Scan feature

### LINKED ISSUE #67: Very high RAM usage
My app is intending to write a total of around 3.6 GiB to the database. Keys are all 32 bytes long and values are all around 4 KiB.

```
[i] Encrypting 9 files from "test_data" (3.596GiB)
[?] Enter master key: ;
[i] Processing key...
[+] Sealing test_data/1k.data (1KiB)
[+] Sealing test_data/2m.data (2MiB)
[+] Sealing test_data/4k.data (4KiB)
[+] Sealing test_data/checksum.json (450B)
[+] Sealing test_data/folder/32m.data (32MiB)
[+] Sealing test_data/folder/64m.data (64MiB)
[+] Sealing test_data/folder/large/1g.data (1GiB)
[+] Sealing test_data/folder/large/2g.data (2GiB)
[+] Sealing test_data/folder/large/512m.data (512MiB)
[i] Syncing data with disk...
[i] Compacting database...
[1]    18243 killed     ./gravity seal test_data
```

That last line there where the process is killed during the `Merge` operation is due to the application using around 13 GB of RAM and being killed by the operating system. Before the merge operation, memory usage peaked at around 7-8 GB.

### PR DESCRIPTION
**Pull request by prologic**
Fixes #67 -- Make searching keys/values someone else's problem? Like [Bleve](https://github.com/blevesearch/bleve-bench)?

### CODE REVIEW

**Comment by awnumar** [comment]
Ooh, well since I never used the feature I can't say whether or not this is a good change. However it would reduce complexity and I guess as long as people who need fast prefix searching can still do it, it's okay.

**Comment by prologic** [comment]
Yeah that's a good point. I think I want to hear from @jsign too. My gut says that an Adapative Radix tree could entirely replace the keydir (_I did try and it almost completely passed all tests, but did run into a couple of minor implementation issues_)

**Comment by jsign** [comment]
A very idiomatic Go solution: simplify. I guess makes sense. 
I subscribe to the idea that someone might implement this themselves quite easily.
Maybe some words in the README would be useful for the reader.

Using radix trees for the `keydir` makes sense since _keys_ distribution isn't expected to be random but mostly _prefixed_; so good for memory footprint. What, a priori, isn't clear to me is the tradeoff between memory savings and `MB/s` throughput compared to `map[string]`. I guess benchmarks will say.

**Comment by prologic** [comment]
My initial benchmark test results demonstratively showed that there was
negligible difference in performance or throughout using N Adaptive Radix
Tree
-- 

James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by prologic** [comment]
And if you recall we actually use a `map[uint64]Item` and an fnv hash of the keys. I'm sure there is a slight cost to computing the hash of a key (byte slice) as there is a cost to converting to `string` (_but we don't map strings_).

I suspect the ART tree is faster or just as fast because it only deals with bytes and has near hash-table performance for most cases due to its adaptive nature

**Comment by jsign** [comment]
Yes, after my comment I noticed the other PR. Quite impressive results.

Yes, I also remember `map[int64]` change, you're right. Besides computing the hash, it's much better since not using strings put much less GC pressure.

**Comment by prologic** [comment]
So... I think what I'll do is merge the #71 as-is since it is a major improvement and keep working on replacing the keydir entirely with the ART tree. Once I can get that working correctly I'll put up another PR to show the performance differences (_if any_) and we can finally close off #67

**Comment by prologic** [comment]
Closing in favor of #74

**Pull request closed without merging**
