### PR TITLE
Uses []byte byte slices as keys directly avoiding serialing string(s)

### LINKED ISSUE #44: Put() to use []byte byte slices (breaking API)
Also off the back of #33 is the possibility of breaking the API (_while we still can!_) and change the signature of `Put()` from:

```#!go
func (b *Bitcask) Put(key string, value []byte) error
```

To:

```#!go
func (b *Bitcask) Put(key, value []byte) error
```

Apparently this is more flexible according to @awnumar and I see more implementations do this than don't. I _believe_ the only real concrete value this adds is the ability to then have keys that are non-ASCI.

### PR DESCRIPTION
**Pull request by prologic**
Closes #44

**NB:** This is a breaking chnage.

### CODE REVIEW

**Comment by awnumar** [comment]
Have you ran any benchmarks to assess the performance impact of this change?

**Comment by prologic** [comment]
I have... And it's actually slightly worse :/ I'm not sure why its counter intuitive.

**Comment by awnumar** [comment]
Wew. Gonna look through the CPU trace.

```
goos: linux
goarch: amd64
pkg: github.com/prologic/bitcask
BenchmarkGet/128B-2         	 1000000	      1079 ns/op	 118.62 MB/s
BenchmarkGet/128BWithPool-2 	 1000000	      1110 ns/op	 115.22 MB/s
BenchmarkGet/256B-2         	 1000000	      1166 ns/op	 219.41 MB/s
BenchmarkGet/256BWithPool-2 	 1000000	      1141 ns/op	 224.24 MB/s
BenchmarkGet/512B-2         	 1000000	      1243 ns/op	 411.73 MB/s
BenchmarkGet/512BWithPool-2 	 2000000	      1209 ns/op	 423.39 MB/s
BenchmarkGet/1K-2           	 1000000	      1363 ns/op	 750.77 MB/s
BenchmarkGet/1KWithPool-2   	 1000000	      1288 ns/op	 795.00 MB/s
BenchmarkGet/2K-2           	 1000000	      1805 ns/op	1134.41 MB/s
BenchmarkGet/2KWithPool-2   	 1000000	      1548 ns/op	1322.32 MB/s
BenchmarkGet/4K-2           	  500000	      2711 ns/op	1510.41 MB/s
BenchmarkGet/4KWithPool-2   	 1000000	      2188 ns/op	1871.35 MB/s
BenchmarkGet/8K-2           	  300000	      4343 ns/op	1885.96 MB/s
BenchmarkGet/8KWithPool-2   	  500000	      3476 ns/op	2356.68 MB/s
BenchmarkGet/16K-2          	  200000	      7309 ns/op	2241.52 MB/s
BenchmarkGet/16KWithPool-2  	  200000	      5453 ns/op	3004.26 MB/s
BenchmarkGet/32K-2          	  100000	     14260 ns/op	2297.86 MB/s
BenchmarkGet/32KWithPool-2  	  200000	      9640 ns/op	3399.05 MB/s
BenchmarkPut/128B-2         	  500000	      3976 ns/op	  32.19 MB/s
BenchmarkPut/256B-2         	  200000	      5567 ns/op	  45.98 MB/s
BenchmarkPut/512B-2         	  200000	      8334 ns/op	  61.43 MB/s
BenchmarkPut/1K-2           	  100000	     25868 ns/op	  39.58 MB/s
BenchmarkPut/2K-2           	   50000	     26219 ns/op	  78.11 MB/s
BenchmarkPut/4K-2           	   30000	     91146 ns/op	  44.94 MB/s
BenchmarkPut/8K-2           	   20000	     96606 ns/op	  84.80 MB/s
BenchmarkPut/16K-2          	   10000	    298734 ns/op	  54.84 MB/s
BenchmarkPut/32K-2          	    5000	    350577 ns/op	  93.47 MB/s
BenchmarkScan-2             	  500000	      2306 ns/op
PASS
ok  	github.com/prologic/bitcask	53.274s
```

**Comment by awnumar** [comment]
What specifically is slower in your tests?

**Comment by awnumar** [comment]
Here's the trace on my system:

[prof.zip](https://github.com/prologic/bitcask/files/3472273/prof.zip)

**Comment by prologic** [comment]
Can you run a before and after on your system? I expected just dealing with byte slices and not serialing strings to byte slices to bt a bit faster.

Before;

```
$ make bench
...
goos: darwin
goarch: amd64
pkg: github.com/prologic/bitcask
BenchmarkGet/128B-4         	  300000	      3923 ns/op	  32.63 MB/s	     387 B/op	       4 allocs/op
BenchmarkGet/128BWithPool-4 	  300000	      3984 ns/op	  32.13 MB/s	     227 B/op	       3 allocs/op
BenchmarkGet/256B-4         	  300000	      3886 ns/op	  65.87 MB/s	     643 B/op	       4 allocs/op
BenchmarkGet/256BWithPool-4 	  300000	      4335 ns/op	  59.05 MB/s	     355 B/op	       3 allocs/op
BenchmarkGet/512B-4         	  300000	      4449 ns/op	 115.08 MB/s	    1187 B/op	       4 allocs/op
BenchmarkGet/512BWithPool-4 	  300000	      4925 ns/op	 103.96 MB/s	     611 B/op	       3 allocs/op
BenchmarkGet/1K-4           	  200000	      5674 ns/op	 180.44 MB/s	    2275 B/op	       4 allocs/op
BenchmarkGet/1KWithPool-4   	  200000	      6525 ns/op	 156.93 MB/s	    1123 B/op	       3 allocs/op
BenchmarkGet/2K-4           	  200000	      6694 ns/op	 305.92 MB/s	    4451 B/op	       4 allocs/op
BenchmarkGet/2KWithPool-4   	  200000	      6942 ns/op	 294.99 MB/s	    2147 B/op	       3 allocs/op
BenchmarkGet/4K-4           	  200000	      8138 ns/op	 503.31 MB/s	    9059 B/op	       4 allocs/op
BenchmarkGet/4KWithPool-4   	  200000	      8466 ns/op	 483.77 MB/s	    4195 B/op	       3 allocs/op
BenchmarkGet/8K-4           	  200000	     10699 ns/op	 765.61 MB/s	   17763 B/op	       4 allocs/op
BenchmarkGet/8KWithPool-4   	  200000	      9358 ns/op	 875.33 MB/s	    8291 B/op	       3 allocs/op
BenchmarkGet/16K-4          	  100000	     14183 ns/op	1155.16 MB/s	   34915 B/op	       4 allocs/op
BenchmarkGet/16KWithPool-4  	  100000	     12121 ns/op	1351.66 MB/s	   16483 B/op	       3 allocs/op
BenchmarkGet/32K-4          	   50000	     23096 ns/op	1418.75 MB/s	   73827 B/op	       4 allocs/op
BenchmarkGet/32KWithPool-4  	  100000	     19303 ns/op	1697.47 MB/s	   32867 B/op	       3 allocs/op
BenchmarkPut/128B-4         	  100000	     14501 ns/op	   8.83 MB/s	     441 B/op	       6 allocs/op
BenchmarkPut/256B-4         	  100000	     15381 ns/op	  16.64 MB/s	     571 B/op	       6 allocs/op
BenchmarkPut/512B-4         	  100000	     21983 ns/op	  23.29 MB/s	     861 B/op	       6 allocs/op
BenchmarkPut/1K-4           	   50000	     29017 ns/op	  35.29 MB/s	    1443 B/op	       6 allocs/op
BenchmarkPut/2K-4           	   30000	     42855 ns/op	  47.79 MB/s	    2606 B/op	       6 allocs/op
BenchmarkPut/4K-4           	   20000	     75782 ns/op	  54.05 MB/s	    5187 B/op	       6 allocs/op
BenchmarkPut/8K-4           	   10000	    127408 ns/op	  64.30 MB/s	    9845 B/op	       6 allocs/op
BenchmarkPut/16K-4          	   10000	    212897 ns/op	  76.96 MB/s	   18883 B/op	       6 allocs/op
BenchmarkPut/32K-4          	    5000	    346810 ns/op	  94.48 MB/s	   41581 B/op	       7 allocs/op
BenchmarkScan-4             	 1000000	      1855 ns/op	     408 B/op	      16 allocs/op
```

After:

```
goos: darwin
goarch: amd64
pkg: github.com/prologic/bitcask
BenchmarkGet/128B-4         	  200000	      5339 ns/op	  23.97 MB/s	     400 B/op	       5 allocs/op
BenchmarkGet/128BWithPool-4 	  300000	      4884 ns/op	  26.20 MB/s	     240 B/op	       4 allocs/op
BenchmarkGet/256B-4         	  300000	      4939 ns/op	  51.82 MB/s	     656 B/op	       5 allocs/op
BenchmarkGet/256BWithPool-4 	  300000	      4921 ns/op	  52.01 MB/s	     368 B/op	       4 allocs/op
BenchmarkGet/512B-4         	  300000	      5283 ns/op	  96.91 MB/s	    1200 B/op	       5 allocs/op
BenchmarkGet/512BWithPool-4 	  200000	      6163 ns/op	  83.07 MB/s	     624 B/op	       4 allocs/op
BenchmarkGet/1K-4           	  200000	      5758 ns/op	 177.82 MB/s	    2288 B/op	       5 allocs/op
BenchmarkGet/1KWithPool-4   	  300000	      6200 ns/op	 165.14 MB/s	    1136 B/op	       4 allocs/op
BenchmarkGet/2K-4           	  200000	      7133 ns/op	 287.09 MB/s	    4464 B/op	       5 allocs/op
BenchmarkGet/2KWithPool-4   	  200000	      6890 ns/op	 297.24 MB/s	    2160 B/op	       4 allocs/op
BenchmarkGet/4K-4           	  200000	      9018 ns/op	 454.20 MB/s	    9072 B/op	       5 allocs/op
BenchmarkGet/4KWithPool-4   	  200000	      7607 ns/op	 538.42 MB/s	    4208 B/op	       4 allocs/op
BenchmarkGet/8K-4           	  200000	     10335 ns/op	 792.57 MB/s	   17776 B/op	       5 allocs/op
BenchmarkGet/8KWithPool-4   	  200000	      9030 ns/op	 907.19 MB/s	    8304 B/op	       4 allocs/op
BenchmarkGet/16K-4          	  100000	     14448 ns/op	1133.93 MB/s	   34928 B/op	       5 allocs/op
BenchmarkGet/16KWithPool-4  	  100000	     12007 ns/op	1364.43 MB/s	   16496 B/op	       4 allocs/op
BenchmarkGet/32K-4          	  100000	     22883 ns/op	1431.97 MB/s	   73840 B/op	       5 allocs/op
BenchmarkGet/32KWithPool-4  	  100000	     17987 ns/op	1821.70 MB/s	   32880 B/op	       4 allocs/op
BenchmarkPut/128B-4         	  100000	     13540 ns/op	   9.45 MB/s	     457 B/op	       8 allocs/op
BenchmarkPut/256B-4         	  100000	     15016 ns/op	  17.05 MB/s	     587 B/op	       8 allocs/op
BenchmarkPut/512B-4         	  100000	     19281 ns/op	  26.55 MB/s	     877 B/op	       8 allocs/op
BenchmarkPut/1K-4           	   50000	     27140 ns/op	  37.73 MB/s	    1459 B/op	       8 allocs/op
BenchmarkPut/2K-4           	   30000	     41205 ns/op	  49.70 MB/s	    2622 B/op	       8 allocs/op
BenchmarkPut/4K-4           	   20000	     71516 ns/op	  57.27 MB/s	    5203 B/op	       8 allocs/op
BenchmarkPut/8K-4           	   10000	    124489 ns/op	  65.80 MB/s	    9861 B/op	       8 allocs/op
BenchmarkPut/16K-4          	   10000	    203266 ns/op	  80.60 MB/s	   18899 B/op	       8 allocs/op
BenchmarkPut/32K-4          	    5000	    361552 ns/op	  90.63 MB/s	   41621 B/op	       9 allocs/op
BenchmarkScan-4             	  500000	      2597 ns/op	     424 B/op	      35 allocs/op
```

**Comment by awnumar** [comment]
There's lots of string conversions in this code. Maybe that is hindering performance?

**Comment by prologic** [comment]
Maybe but it doesn't show up in the CPU profile(s) very well if at all. So I'm not sure tbh. I think we'll wait for @jsign to put up the custom encoder/decoder (#42) and merge this then at the same time and keep improving/optimizing.

**Pull request merged**
