### PR TITLE
Gv/issue 165 unlock race condition

### PR DESCRIPTION
**Pull request by LeGEC**
Fix race condition described in [#165](https://github.com/prologic/bitcask/issues/165)

### CODE REVIEW

**Comment by LeGEC** [comment]
Known limitations of the proposed fix :

* linux and macos only (implemented using "flock"), no windows implementation in this first version
* only Lock/TryLock are implemented, no RLock/TryRLock implementation
* the 'Unlock' function proposed in this PR removes the lockfile from disk

the above are suitable for bitcask's use of an empty "lock" file located in the directory, but should not be used to, say, take a lock on a file you want to edit.

**Comment by prologic** [comment]
LGTM (_mostly_). Can you fix the failing builds in CI? I'll try this out locally on some of my projects that use Bitcaks tonight.

**Comment by prologic** [comment]
I did some testing with this finally and so far so good. Just trying to fix the CI build failures before merging.

@LeGEC What's the plan to support Windows? (_as much as I don't really care to!_)

**Comment by prologic** [comment]
Latest Windows build failures:

```
# github.com/prologic/bitcask/flock
##[error]flock\flock.go:45:13: undefined: lock_sys
##[error]flock\flock.go:48:13: undefined: lock_sys
##[error]flock\flock.go:71:13: undefined: lock_sys
##[error]flock\flock.go:90:10: undefined: rm_if_match
```

I _think_ if we don't include an `flock_windows.go` we're just breaking the library's existing support for no good reason. Can we add one?

**Comment by LeGEC** [comment]
Do you know someone who could write the implementation for windows ?

**Comment by prologic** [comment]
> Do you know someone who could write the implementation for windows ?

No sadly I don't. Hmmm 🤔

I guess we can drop Windows support for the time being? What do you think?

**Pull request merged**
