### PR TITLE
Add a new custom trie implemtnation for prefix scans

### LINKED ISSUE #67: Very high RAM usage
My app is intending to write a total of around 3.6 GiB to the database. Keys are all 32 bytes long and values are all around 4 KiB.

```
[i] Encrypting 9 files from "test_data" (3.596GiB)
[?] Enter master key: ;
[i] Processing key...
[+] Sealing test_data/1k.data (1KiB)
[+] Sealing test_data/2m.data (2MiB)
[+] Sealing test_data/4k.data (4KiB)
[+] Sealing test_data/checksum.json (450B)
[+] Sealing test_data/folder/32m.data (32MiB)
[+] Sealing test_data/folder/64m.data (64MiB)
[+] Sealing test_data/folder/large/1g.data (1GiB)
[+] Sealing test_data/folder/large/2g.data (2GiB)
[+] Sealing test_data/folder/large/512m.data (512MiB)
[i] Syncing data with disk...
[i] Compacting database...
[1]    18243 killed     ./gravity seal test_data
```

That last line there where the process is killed during the `Merge` operation is due to the application using around 13 GB of RAM and being killed by the operating system. Before the merge operation, memory usage peaked at around 7-8 GB.

### PR DESCRIPTION
**Pull request by prologic**
THis is a very quick attempt at solving #67 

Based on [ryancaille/trie](https://github.com/ryancaille/trie) and _slightly modified_ this should have significantly less impact on allocations and memory.

@awnumar @jsign Are you able to help test this branch? Feedback/Improvements welcome!

Fixes #67 (_assuming @awnumar application / use-case resolved #67_)

### CODE REVIEW

**Comment by prologic** [comment]
I _believe_ we just sped up Prefix Key Scans and reduced memory allocations by a fair bit:

Before:

```#!sh
$ make bench
...
BenchmarkScan-4             	  200000	      6370 ns/op	     392 B/op	      30 allocs/op
```

After:

```#!sh
$ make bench
...
BenchmarkScan-4             	 1000000	      1679 ns/op	     408 B/op	      16 allocs/op
```

- ~3-4x faster
- 50% reduction in allocs

**Comment by prologic** [comment]
This seems to result in much better memory usage following what @jsign did in #67 

Hoping one / both of you can confirm :)

Screen Shot 2019-08-24 at 10 07 51 PM

**Comment by awnumar** [comment]
On my system testing with a new reduced data-set of ~3GB results in 2.3GB of system memory being used by the process with greedy scan enabled, and 289.4MB with it disabled. The same test on master results in memory usage of ~6.8GB, a delta of 98.9%.

I did not have it merge the database on closing which tends to use a lot of memory due to its implementation essentially working by reading everything into RAM and writing it back to a fresh database.

**Comment by awnumar** [comment]
I just had a thought about adding items to the database twice (duplicate key). Is the trie node also duplicated?

Also during merge, is a second trie structure created and populated instead of the original being reused?

**Comment by prologic** [comment]
> I just had a thought about adding items to the database twice (duplicate key). Is the trie node also duplicated?

No duplicate keys are never added as additional nodes. Just one set of nodes per key.

https://github.com/prologic/bitcask/blob/a999d3466fda08a65566da4c45682169a682c020/internal/trie/node.go#L39-L45
 
> Also during merge, is a second trie structure created and populated instead of the original being reused?

A new one is created every time the database  is reopened (_which happens after a merge_)

https://github.com/prologic/bitcask/blob/a999d3466fda08a65566da4c45682169a682c020/bitcask.go#L319-L322

----

So this implementation is better by what in your  use-case? But its still somewhat expensive?

**Comment by prologic** [comment]
Hmmmm in my tests on this branch I can no longer repro trie being greedy about memory. The heap shows all the memory being used by the keydir now. What am I dong wrong? :)

**Comment by awnumar** [comment]
> Hmmmm in my tests on this branch I can no longer repro trie being greedy about memory. The heap shows all the memory being used by the keydir now. What am I dong wrong? :)

profile001

**Comment by awnumar** [comment]
> A new one is created every time the database is reopened (which happens after a merge)

Would probably be better just to reassign and reuse the existing structure in this case.

> So this implementation is better by what in your use-case? But its still somewhat expensive?

This implementation seems to use about half as much memory in my use case, but still significantly more than with greedyScan disabled.

**Comment by prologic** [comment]
@jsign What are your thoughts here?

**Comment by prologic** [comment]
Doing some more research on tries / radix trees in general and reading this [post](https://medium.com/basecs/compressing-radix-trees-without-too-many-tears-a2e658adb9a0) ...

I think we can merge this PR as a improvement? @awnumar ?

But let's open a new issue (_closing #67_) to further optimize the trie implementation? I _think_ there are still areas for improvement!

**Comment by jsign** [comment]
I compared `BenchmarkScan` and can't seem to reproduce your speedups.

`master - a20ee3e `:
```
goos: linux
goarch: amd64
pkg: github.com/prologic/bitcask
BenchmarkScan-8           200000              6176 ns/op             390 B/op         29 allocs/op
BenchmarkScan-8           300000              4786 ns/op             390 B/op         29 allocs/op
BenchmarkScan-8           200000              5449 ns/op             390 B/op         29 allocs/op
BenchmarkScan-8           200000              6096 ns/op             390 B/op         29 allocs/op
BenchmarkScan-8           200000              5139 ns/op             390 B/op         29 allocs/op
BenchmarkScan-8           200000              5297 ns/op             390 B/op         29 allocs/op
BenchmarkScan-8           200000              6235 ns/op             390 B/op         29 allocs/op
BenchmarkScan-8           200000              5877 ns/op             390 B/op         29 allocs/op
BenchmarkScan-8           300000              4859 ns/op             390 B/op         29 allocs/op
BenchmarkScan-8           200000              6200 ns/op             390 B/op         29 allocs/op
PASS
ok      github.com/prologic/bitcask     16.711s
```

`new_trie - 131c9b7`:
```
goos: linux
goarch: amd64
pkg: github.com/prologic/bitcask
BenchmarkScan-8           200000              6503 ns/op             392 B/op         30 allocs/op
BenchmarkScan-8           300000              5128 ns/op             392 B/op         30 allocs/op
BenchmarkScan-8           300000              5837 ns/op             392 B/op         30 allocs/op
BenchmarkScan-8           200000              5900 ns/op             392 B/op         30 allocs/op
BenchmarkScan-8           300000              4623 ns/op             392 B/op         30 allocs/op
BenchmarkScan-8           200000              6252 ns/op             392 B/op         30 allocs/op
BenchmarkScan-8           200000              6411 ns/op             392 B/op         30 allocs/op
BenchmarkScan-8           300000              5016 ns/op             392 B/op         30 allocs/op
BenchmarkScan-8           200000              6644 ns/op             392 B/op         30 allocs/op
BenchmarkScan-8           300000              5519 ns/op             392 B/op         30 allocs/op
PASS
```
Comparison:
```
name    old time/op    new time/op    delta
Scan-8    5.61µs ±15%    5.78µs ±20%    ~     (p=0.481 n=10+10)

name    old alloc/op   new alloc/op   delta
Scan-8      390B ± 0%      392B ± 0%  +0.51%  (p=0.000 n=10+10)

name    old allocs/op  new allocs/op  delta
Scan-8      29.0 ± 0%      30.0 ± 0%  +3.45%  (p=0.000 n=10+10)
```
Am I missing something?

**Comment by prologic** [comment]
I think @awnumar was able to confirm the reduction in memory and speedups? I did `git push -f` a few times so maybe just double check you're actually on the HEAD of that branch with a `git reset --hard ...`? Just to be sure :)

Either way I'll double check in a few hours...

Also I think we should probably use a Radix Tree here in stead or otherwise known as a compact trie or patricia tree -- They are more space optimized as they remove redundant nodes which a standard trie does not.

**Comment by jsign** [comment]
A step-by-step of my procedure might help:
```
(master) % git status                                                                                                                            ~/code/bitcask
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
(master) % git rev-parse HEAD                                                                                                                    ~/code/bitcask
a20ee3e3d4b14354aa18f0d8976e2e3cb10247d8
(master) % go test -run none -bench=BenchmarkScan -benchmem -count 5                                                                             ~/code/bitcask
goos: linux
goarch: amd64
pkg: github.com/prologic/bitcask
BenchmarkScan-8           200000              6591 ns/op             390 B/op         29 allocs/op
BenchmarkScan-8           200000              6299 ns/op             390 B/op         29 allocs/op
BenchmarkScan-8           200000              6638 ns/op             390 B/op         29 allocs/op
BenchmarkScan-8           200000              6146 ns/op             390 B/op         29 allocs/op
BenchmarkScan-8           200000              6241 ns/op             390 B/op         29 allocs/op
PASS
ok      github.com/prologic/bitcask     9.830s
(master) % git checkout new_trie                                                                                                                 ~/code/bitcask
Switched to branch 'new_trie'
Your branch is up to date with 'origin/new_trie'.
(new_trie) % git rev-parse HEAD                                                                                                                  ~/code/bitcask
131c9b7bcadd3b2a2c9b75cc252af9afea2846ae
(new_trie) % go test -run none -bench=BenchmarkScan -benchmem -count 5                                                                           ~/code/bitcask
goos: linux
goarch: amd64
pkg: github.com/prologic/bitcask
BenchmarkScan-8           200000              6469 ns/op             392 B/op         30 allocs/op
BenchmarkScan-8           200000              6453 ns/op             392 B/op         30 allocs/op
BenchmarkScan-8           200000              6460 ns/op             392 B/op         30 allocs/op
BenchmarkScan-8           200000              6358 ns/op             392 B/op         30 allocs/op
BenchmarkScan-8           200000              6693 ns/op             392 B/op         30 allocs/op
PASS
ok      github.com/prologic/bitcask     9.942s
(new_trie) %                                                                                                                                     ~/code/bitcask
```

**Comment by prologic** [comment]
I  think you're right; I repeated your steps on my work Macbook Pro and got the same results:

```
james@Jamess-MacBook-Pro
Mon Aug 26 11:15:43
~/Contributions/bitcask
 (master) 0
$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

james@Jamess-MacBook-Pro
Mon Aug 26 11:15:44
~/Contributions/bitcask
 (master) 0
$ git rev-parse HEAD
a20ee3e3d4b14354aa18f0d8976e2e3cb10247d8

james@Jamess-MacBook-Pro
Mon Aug 26 11:15:51
~/Contributions/bitcask
 (master) 0
$ go test -run none -bench=BenchmarkScan -benchmem -count 5
go: downloading golang.org/x/exp v0.0.0-20190731235908-ec7cb31e5a56
go: extracting golang.org/x/exp v0.0.0-20190731235908-ec7cb31e5a56
goos: darwin
goarch: amd64
pkg: github.com/prologic/bitcask
BenchmarkScan-4   	  200000	      6254 ns/op	     390 B/op	      29 allocs/op
BenchmarkScan-4   	  200000	      5878 ns/op	     390 B/op	      29 allocs/op
BenchmarkScan-4   	  200000	      6182 ns/op	     390 B/op	      29 allocs/op
BenchmarkScan-4   	  200000	      6215 ns/op	     390 B/op	      29 allocs/op
BenchmarkScan-4   	  200000	      5885 ns/op	     390 B/op	      29 allocs/op
PASS
ok  	github.com/prologic/bitcask	6.526s

james@Jamess-MacBook-Pro
Mon Aug 26 11:16:08
~/Contributions/bitcask
 (master) 0
$ git checkout new_trie
Branch 'new_trie' set up to track remote branch 'new_trie' from 'origin'.
Switched to a new branch 'new_trie'

james@Jamess-MacBook-Pro
Mon Aug 26 11:16:19
~/Contributions/bitcask
 (new_trie) 0
$ git rev-parse HEAD
131c9b7bcadd3b2a2c9b75cc252af9afea2846ae

james@Jamess-MacBook-Pro
Mon Aug 26 11:16:25
~/Contributions/bitcask
 (new_trie) 0
$ go test -run none -bench=BenchmarkScan -benchmem -count 5
goos: darwin
goarch: amd64
pkg: github.com/prologic/bitcask
BenchmarkScan-4   	  200000	      6001 ns/op	     392 B/op	      30 allocs/op
BenchmarkScan-4   	  200000	      5943 ns/op	     392 B/op	      30 allocs/op
BenchmarkScan-4   	  200000	      6087 ns/op	     392 B/op	      30 allocs/op
BenchmarkScan-4   	  200000	      6054 ns/op	     392 B/op	      30 allocs/op
BenchmarkScan-4   	  200000	      5501 ns/op	     392 B/op	      30 allocs/op
PASS
ok  	github.com/prologic/bitcask	6.374s
```

I must have goofeed something up :)

**Comment by prologic** [comment]
@jsign Do you have spare cycles to play with https://github.com/armon/go-radix here?

**Comment by jsign** [comment]
Little time at the moment, hopefully in some days/week a more organized spare time.
Might help in discussion burst though.

**Comment by prologic** [comment]
No worries! I'm going to close this PR as _invalid_ after reconfirming results. I'll probably work on a radix tree implementation tonight and retest #67 -- Hopefully @awnumar is able to help compare with his use-case/dataset.

**Pull request closed without merging**
