### PR TITLE
RFC: Collections and DataTypes

### PR DESCRIPTION
**Pull request by prologic**
Toying with the idea of adding convenience methods for various data-types as well collections.

Example:

```#!go
func main()  {
  db, _ := bitcask.Open("mydb")
  db.PutInt("foo", 1234")
  val, _ = db.GetInt("foo")
}
```

```
$ go test -v -failfast -run TestInts .
=== RUN   TestInts
=== RUN   TestInts/Open
=== RUN   TestInts/PutInt
=== RUN   TestInts/GetInt
=== RUN   TestInts/Close
--- PASS: TestInts (0.02s)
    --- PASS: TestInts/Open (0.00s)
    --- PASS: TestInts/PutInt (0.00s)
    --- PASS: TestInts/GetInt (0.00s)
    --- PASS: TestInts/Close (0.02s)
PASS
ok  	github.com/prologic/bitcask	0.043s
```

### CODE REVIEW

**Comment by awnumar** [comment]
Perhaps one for byte slice indexing:

```go
func (b *Bitcask) Put(key, value []byte) ...
```

Otherwise you have to write something like:

```go
b.Put(fmt.Sprintf("%x", key), value)
```

**Comment by prologic** [comment]
> Perhaps one for byte slice indexing:
> 
> ```go
> func (b *Bitcask) Put(key, value []byte) ...
> ```
> 
> Otherwise you have to write something like:
> 
> ```go
> b.Put(fmt.Sprintf("%x", key), value)
> ```

I actually wondered whether the API should have used `[]byte` slices for keys all along... Many implementations do. Is it too late to change? :)

**Comment by prologic** [comment]
Also the general idea behind this PR (_I regard it as experimental at best at the moment_); was to see what it would be like to add convenient API to remove a lot of boilerplate you might end up with in your code by directly using `Bitcask.Get()`, `Bitcask.Put()` and friends.

Once I had basic types handled; I was going to support encoding/decoding structs. In the back of my mind I was also thinking about how to encode lists and sets. Is this crazy? :)

**Comment by awnumar** [comment]
Byte slices would have made things more flexible but I don't think it's worth a breaking change. Perhaps a new method that accepts bytes (without the overhead of encoding them even?)

In terms of additional features like lists, etc, I assume you're talking about serialisation of data types? There's likely already libraries that do this so I'm not sure if it's worth adding. The set of dependencies this project has is already quite sizable. Just my opinion though :)

**Comment by prologic** [comment]
> Byte slices would have made things more flexible but I don't think it's worth a breaking change. Perhaps a new method that accepts bytes (without the overhead of encoding them even?)

Do you have a suggested signature in mind?

> In terms of additional features like lists, etc, I assume you're talking about serialisation of data types? There's likely already libraries that do this so I'm not sure if it's worth adding. The set of dependencies this project has is already quite sizable. Just my opinion though :)

Yeah I actually agree; and opinions are valuable! Thank you :) -- I believe many dependeices get dragged in because of the use of Protobuf (_sigh_). Anyway... Happy to reduce the scope of this PR considerably (_it was only an idea_). Open to suggestions:) (_even if it's reduced to just adding byte slice keys are you mentioend_)

**Comment by awnumar** [comment]
> Do you have a suggested signature in mind?

```go
func (b *Bitcask) PutRaw(key, value []byte) error { /* ... */ }
func (b *Bitcask) PutBytes(key, value []byte) error { /* ... */ }
```
Could work? I'm not sure about the ergonomics.

> I believe many dependeices get dragged in because of the use of Protobuf

Is protobuf actually needed? Looking at where the entries are serialised,

https://github.com/prologic/bitcask/blob/8b684b635de2367c1776e57046a021752e731283/internal/entry.go#L9-L17

It looks as though you can get away with doing what the original paper does.

```
{uint32 key size}{uint64 value size}{key}{value}{checksum}
^--------------12 bytes-----------^
```

**Comment by awnumar** [comment]
Also if the checksum was computed on key + value, it would tie each key to the right value as well.

**Comment by prologic** [comment]
Looks like we're having two different discussions at once :) But that's okay!

How does `PutRaw(...)` differ from `PutBytes(...)`? They look weirdly identical to me :)

Re use of Protobuf -- You are right! I admit I was a bit lazy and didn't go to all the effort of hand-writing a custom encoder/decoder -- I suspect it _may_ be more efficient/faster if we did! /cc @jsign  :D -- Would you mind filding a separate issue on this so we can explore this more? (_I have to admit I kind of detest how much Protobuf adds to a project and resulting binary's weight :/_)

**Comment by awnumar** [comment]
> They look weirdly identical to me

They are :) I was suggesting alternate names.

**Comment by prologic** [comment]
D'oh don't I feel silly! I blame it being 10pm at night :)

**Comment by prologic** [comment]
Closing this and the PR/branch (_as you said @awnumar there are libraries for this_) in favor of separate discussions in #44 and #42

**Comment by prologic** [comment]
I got a little bored one day and wanted to see what implementing different container collections was like atop a key/value store. Here's one for a List backed by Bitcask:

```#!go
package bitcask

import (
	"encoding/binary"
	"errors"
	"fmt"
)

const (
	int64Size = 8
)

var (
	// ErrIndexOutOfRange returned when indexing outside of the bounds of a list
	ErrIndexOutOfRange = errors.New("error: index out of range")
)

// List defines an interface for a container type that holds a list of values
// backed by underlying key/value pairs in a Bitcask database
type List interface {
	Append(value string) error
	Clear() error
	Count() (int64, error)
	Extend(values []string) error
	Index(value string) (int64, error)
	Insert(index int64, value string) error
	Pop(index int64) (string, error)
	Remove(index int64) error
}

type list struct {
	db *Bitcask

	Name string
}

// List returned a new container that holds a list of values
func (b *Bitcask) List(name string) List {
	return &list{db: b, Name: name}
}

func (l *list) formatKey(suffix string) []byte {
	return []byte(fmt.Sprintf("%s/{LIST}/%s", l.Name, suffix))
}

func (l *list) Append(value string) error {
	index, err := l.Count()
	if err != nil {
		return err
	}

	if err := l.db.Put(l.formatKey(string(index)), []byte(value)); err != nil {
		return err
	}

	index++

	// TODO: Add a Bitcask.Incr(key []byte)?
	buf := make([]byte, int64Size)
	binary.BigEndian.PutUint64(buf, uint64(index))
	if err := l.db.Put(l.formatKey("size"), buf); err != nil {
		return err
	}

	return nil
}

func (l *list) Clear() error {
	index, err := l.Count()
	if err != nil {
		return err
	}

	for index >= 0 {
		if err := l.db.Delete(l.formatKey(string(index))); err != nil {
			return err
		}
		index--
	}

	if err := l.db.Delete(l.formatKey("size")); err != nil {
		return err
	}

	return nil
}

func (l *list) Count() (int64, error) {
	val, err := l.db.Get(l.formatKey("size"))
	if err == ErrKeyNotFound {
		return 0, nil
	}
	if err != nil {
		return 0, err
	}

	n := binary.BigEndian.Uint64(val)

	return int64(n), nil
}

func (l *list) Extend(values []string) error {
	for _, value := range values {
		if err := l.Append(value); err != nil {
			return err
		}
	}

	return nil
}

func (l *list) Index(value string) (int64, error) {
	count, err := l.Count()
	if err != nil {
		return -1, err
	}

	var index int64
	for index = 0; index < count; index++ {
		val, err := l.db.Get(l.formatKey(string(index)))
		if err != nil {
			return -1, err
		}
		if string(val) == value {
			return index, nil
		}
	}

	return -1, nil
}

func (l *list) Insert(index int64, value string) error {
	count, err := l.Count()
	if err != nil {
		return err
	}

	if index < 0 || index > count {
		return ErrIndexOutOfRange
	}

	var i int64
	for i = (count - 1); i > (index + 1); i-- {
		val, err := l.db.Get(l.formatKey(string(i)))
		if err != nil {
			return err
		}
		if err := l.db.Put(l.formatKey(string(i+1)), val); err != nil {
			return err
		}
	}

	if err := l.db.Put(l.formatKey(string(index)), []byte(value)); err != nil {
		return err
	}

	return nil
}

func (l *list) Pop(index int64) (string, error) {
	count, err := l.Count()
	if err != nil {
		return "", err
	}

	if index < 0 || index > count {
		return "", ErrIndexOutOfRange
	}

	value, err := l.db.Get(l.formatKey(string(index)))
	if err != nil {
		return "", err
	}

	var i int64
	for i = (index + 1); i < count; i++ {
		val, err := l.db.Get(l.formatKey(string(i)))
		if err != nil {
			return "", err
		}
		if err := l.db.Put(l.formatKey(string(i-1)), val); err != nil {
			return "", err
		}
	}

	count--

	if err := l.db.Delete(l.formatKey(string(count))); err != nil {
		return "", err
	}

	// TODO: Add a Bitcask.Decr(key []byte)?
	buf := make([]byte, int64Size)
	binary.BigEndian.PutUint64(buf, uint64(count))
	if err := l.db.Put(l.formatKey("size"), buf); err != nil {
		return "", err
	}

	return string(value), nil
}

func (l *list) Remove(index int64) (err error) {
	_, err = l.Pop(index)
	return
}
```

And an example program:

```#!go
package main

import (
	"fmt"
	"log"

	"github.com/prologic/bitcask"
)

func main() {
	db, _ := bitcask.Open("test.db")
	defer db.Close()

	l := db.List("foo")
	if err := l.Append("1"); err != nil {
		log.Fatal(err)
	}
	l.Append("2")
	l.Append("3")
	n, _ := l.Count()
	fmt.Printf("%d values\n", n)

	if err := l.Clear(); err != nil {
		log.Fatal(err)
	}

	if err := l.Extend([]string{"foo", "bar", "baz"}); err != nil {
		log.Fatal(err)
	}

	i, err := l.Index("bar")
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("index of 'bar': %d\n", i)

	if err := l.Insert(1, "hello"); err != nil {
		log.Fatal(err)
	}

	val, err := l.Pop(1)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("val: %s\n", val)

	err = l.Remove(1)
	if err != nil {
		log.Fatal(err)
	}
}
```

When run the resulting database looks like this:

```
$ ./bitcask -p ./test.db dump | jq '{key: .key | @base64d, value: .value | @base64d}'
{
  "key": "foo/{LIST}/\u0000",
  "value": "foo"
}
{
  "key": "foo/{LIST}/size",
  "value": "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001"
}
```

**Pull request closed without merging**
