### PR TITLE
Add flock implementation for Windows

### PR DESCRIPTION
**Pull request by watermint**

### CODE REVIEW

**Review by prologic — COMMENTED** [review]
Hey! Thanks for this PR! 

Do you mind adding another commit to bring back the Windows testing I removed recently since this PR should fix the reason I removed it in the first place 👌

**Comment by watermint** [comment]
Thanks for confirming. I'll add those tests.

**Comment by prologic** [comment]
I would just recover the ones I deleted from Git history 😁

**Comment by prologic** [comment]
@watermint Are you planning on finishing this PR so we can merge it? :D

**Comment by NicoNex** [comment]
Hi, I'm interested in this pr for the Windows support, since I've seen that it has gone stale I could finish it. What needs to be done still?

**Comment by prologic** [comment]
> Hi, I'm interested in this pr for the Windows support, since I've seen that it has gone stale I could finish it. What needs to be done still?

As per my comments, I _think_ you just need to recover the tests specific to Windows for locking and add that to this PR and ensure they pass on Windows of course :)

Thanks for picking this up! I lack a Windows machine myself, so it's hard for me to do this.

**Comment by NicoNex** [comment]
@prologic would you consider using an external package for flock such as [this one](https://github.com/gofrs/flock)?
It seems well done and is cross platform (covering aix as well).

**Comment by prologic** [comment]
Sure I'd it works no worries

**Comment by NicoNex** [comment]
Opened a new pr #219.

**Comment by prologic** [comment]
#219 supersede this. Closing...

**Pull request closed without merging**
