### PR TITLE
Improves encode/decode performance by using a buffer pool

### PR DESCRIPTION
**Pull request by prologic**
Also reduces memory allocations for `.Get()` and `.Put()` by 1.

### CODE REVIEW

**Comment by jsign** [comment]
I think this is a good idea, but I have some questions that may be interesting to have your opinion.
I'm thinking of two questions:
1) Why not also using a pool for the other slice allocation to read the map value? (would save even one more allocation)
2) Why do you choose that buff pool implementation rather than `sync.Pool` from the standard library?

I have some possible answers, but I'd like to know your opinion.
Here are my thoughts about each question:
1) I guess the size unpredictability of the value hurts a bit. The obvious solution is making a pool with a max size equal to `DefaultMaxValueSize`, but that hurts since it may be assuming a worst-case and putting too much memory pressure on this allocation-saving idea.
Also, I assume that the `ReadAll` election was on purpose since size is fixed, but wouldn't be possible in this other slice allocation since the size isn't fixed. That isn't that bad because it would mean reading exactly `n` and resetting the buff before returning to the pool.

2) I thought some minutes about why you might choose this, and I think that predictable latency might be the main reason. I saw the implementation of the dependency and comparing to `sync.Pool`, these are my thoughts:
- `sync.Pool` has an auto-adjust nature of growing and shrinking pool depending on the concurrency level. That's quite nice because in the current pool implementation concurrency is capped by the `maxLimit` which is hard to set up correctly. If concurrency comes close to `maxSize`, the channel used by the buff pool will be a contention point. Using a `sync.Pool` will grow if the concurrency increases, and will release resources on low concurrency situations. On the other hand, if the use of the pool isn't quite uniform the grow-shrink cycle will come closer of not using a buff pool at all and less predictable latency due to allocations.

As always, it's about tradeoffs. Considering how you define bitcask regarding _predictable performance_, it seems that your current choice of a fixed buff mem pool provides the most predictability. Maybe some further explanation of the concurrency level assumed before suffering contention problems would be interesting to explain in the README (or even make it configurable with a default value to not complicate things).

**Comment by prologic** [comment]
> 1. Why not also using a pool for the other slice allocation to read the map value? (would save even one more allocation)

I fully intended to. This is just an early PR :)

Would you like to take it over? :) You might have more bandwidth than i!

> 2. Why do you choose that buff pool implementation rather than `sync.Pool` from the standard library?

Actually I didn't realize there was one in the standard library! No objections to using it!

> 1. I guess the size unpredictability of the value hurts a bit. The obvious solution is making a pool with a max size equal to `DefaultMaxValueSize`, but that hurts since it may be assuming a worst-case and putting too much memory pressure on this allocation-saving idea.
>    Also, I assume that the `ReadAll` election was on purpose since size is fixed, but wouldn't be possible in this other slice allocation since the size isn't fixed. That isn't that bad because it would mean reading exactly `n` and resetting the buff before returning to the pool.

I have no useful insight here; I'm not sure I'd want to sacrifice overheads for performance.
I think keeping overheads down and predictable performance is more important.

> 2. I thought some minutes about why you might choose this, and I think that predictable latency might be the main reason. I saw the implementation of the dependency and comparing to `sync.Pool`, these are my thoughts:

Actually I don't know how the std. lib buffer pool compares in performance.

But you are right; predictable performance and latency is important. Breaking that would break the design and expectations.

> * `sync.Pool` has an auto-adjust nature of growing and shrinking pool depending on the concurrency level. That's quite nice because in the current pool implementation concurrency is capped by the `maxLimit` which is hard to set up correctly. If concurrency comes close to `maxSize`, the channel used by the buff pool will be a contention point. Using a `sync.Pool` will grow if the concurrency increases, and will release resources on low concurrency situations. On the other hand, if the use of the pool isn't quite uniform the grow-shrink cycle will come closer of not using a buff pool at all and less predictable latency due to allocations.

Good point; I think its a matter of trade-offs. The only real way to test the two approaches out would be in a real-world scenario with real-world loads on the database.

> As always, it's about tradeoffs. Considering how you define bitcask regarding _predictable performance_, it seems that your current choice of a fixed buff mem pool provides the most predictability. Maybe some further explanation of the concurrency level assumed before suffering contention problems would be interesting to explain in the README (or even make it configurable with a default value to not complicate things).

You make a good point! The reason I put this PR up in its early form is to get this kind of feedback. On one hand if I use a fixed-size buffer pool I hurt concurrency (_well more than it is now_).

**Comment by prologic** [comment]
At the moment concurrent reads are not limited in any way:

- [bitcask.Get()](https://github.com/prologic/bitcask/blob/master/bitcask.go#L108-L135)
- [internal.Datafile.ReadAt()](https://github.com/prologic/bitcask/blob/master/internal/datafile.go#L136-L158)

So I _think_ introducing this fixed-sized buffer pool _might_ hurt concurrent read performance a fair bit at concurrency > `maxLimit` (_of the fixed sized pool limit_)?

**Comment by jsign** [comment]
Yes, I agree. As you said, not having more information about the context in which will be used implies that any kind of prior decision about `maxLimit` might be wrong for totally different reasons:
- may limit concurrency aggressively (hard cap on concurrency level)
- on very low concurrency, it may impose a memory footprint that is unnecessary

Regarding using buffpool for `values`, has not only the same concurrency discussion as before but also a new one: how big each buf in the pool should be? For this case, what seems obvious is that [bpool.BytePool](https://godoc.org/github.com/oxtoacart/bpool#BytePool) is quite dangerous and may be a better idea to use [bpool.SizedBufferPool](https://godoc.org/github.com/oxtoacart/bpool#SizedBufferPool). This allows imposing a hard limit in the total amount of memory inside the pool since any buf that have grown besides some limit (some outlier value) will be discarded (and eventually GCed). Unfortunately, this also means that there's a new parameter to tune: not only the `maxLimit` but the `maxSize`.

Maybe the real solution is to allow two modes:
- no pools (default): doesn't limit concurrency by any means at the cost of allocations (basically, what is in `master`)
- pools: the client should specify `maxLimit` and 90th percentiles for value sizes. This allows avoiding allocations while safely knowing that concurrency isn't limited. Also, asking for a 90th (or whatever) would allow to not completely avoid allocations for `values` but most of the time yes.

I think that would be a nice feature for the buffpool implementation to haven an option to not blocking if the limit is reached. In that case, just allocate and move on (bad luck for allocation, but completely blocking I think is too much in this situation).

**Comment by prologic** [comment]
I actually like this idea a lot; give the power to the user :) In the fact of no further information giving the user the choice is a good compromise! What's even better is that all of qhat you've described can be done with the "Functional Options" style already implemented for other configurable settings.

**Comment by prologic** [comment]
Feel free to submit a ne PR to supercede mine :)

**Comment by jsign** [comment]
Sure, I'll look for a time slot to try to make it.

I think this involves further refactoring since now the pools are _package scoped_ which doesn't feel quite right since two instances of the database would share the pool. 

Seems that `Encoder` and `Decoder` structs should be one per instance `Datafile` lifetime which owns the pools, but that would change the actual semantics. Something like: `NewDecoder(options ...)`, and `func (e *Encoder) Decode(r io.Reader, v proto.Message)`, which my feel awkward... the actual implementation is idiomatic (compared with similars, e.g. `json.NewEncoder(io.Reader)`).

Going further, a different idea:
`Datafile` scope might be inappropriate since reading from more than one `Datafile` would create more than one pool. Sounds better to be `Bitcask` scoped, maybe something like a new `streampb.NewCodec(poolingConfig)` injected in `Datafile` from which methods in `Datafile` ask for new Encoders or Decoders: `(c *streampb.Codec) NewEncoder` which returns an `Encoder` that uses (or not) a pool.

I'm thinking out loud... hope doesn't sound too complicated.

**Comment by prologic** [comment]
> I think this involves further refactoring since now the pools are package scoped which doesn't feel quite right since two instances of the database would share the pool.

Not sure this is possible anyway; we lock the database per process to prevent accidental data corruption and ensure  data durability.

**Comment by prologic** [comment]
I also realized some of the decoding for key/values of known size and position can be further optimized with a patch like:

```#!diff
diff --git a/internal/datafile.go b/internal/datafile.go
index ad96637..dfb2f27 100644
--- a/internal/datafile.go
+++ b/internal/datafile.go
@@ -1,7 +1,6 @@
 package internal
 
 import (
-	"bytes"
 	"fmt"
 	"os"
 	"path/filepath"
@@ -10,12 +9,14 @@ import (
 	"github.com/pkg/errors"
 	"golang.org/x/exp/mmap"
 
+	"github.com/gogo/protobuf/proto"
 	pb "github.com/prologic/bitcask/internal/proto"
 	"github.com/prologic/bitcask/internal/streampb"
 )
 
 const (
 	DefaultDatafileFilename = "%09d.data"
+	prefixSize              = 8
 )
 
 var (
@@ -151,9 +152,10 @@ func (df *Datafile) ReadAt(index, size int64) (e pb.Entry, err error) {
 		return
 	}
 
-	buf := bytes.NewBuffer(b)
-	dec := streampb.NewDecoder(buf)
-	_, err = dec.Decode(&e)
+	err = proto.Unmarshal(b[prefixSize:], &e)
+	if err != nil {
+		return
+	}
 	return
 }
 ```

Which increases read performance again and reduces allocs by 1/2

**Comment by jsign** [comment]
Duh, that makes a lot of sense :100: 
Better start from there :smile:

**Comment by jsign** [comment]
That means the following situation:
image
Apart from allocs from `proto`... there's the alloc from the return, and the `make`. 

`bufpool` for that `make` can be an option. Now I thought of another possible idea: bucketing bufpools by `size`. The cardinality of `size` shoudn't be too big and that may solve the `maxSize` problem.

**Comment by prologic** [comment]
> bufpool for that make can be an option. Now I thought of another possible idea: bucketing bufpools by size. The cardinality of size shoudn't be too big and that may solve the maxSize problem.

👍

**Comment by prologic** [comment]
So I've confirmed on my 11" Macbook that removing this whole layer of buffers/readers/etc and 1/2 the allocs **does** improve the read path performance:

Before:

```
$ go test -test.run -benchmem -benchtime=5s -bench=BenchmarkGet .
goos: darwin
goarch: amd64
pkg: github.com/prologic/bitcask
BenchmarkGet/128B-4         	 2000000	      4118 ns/op	  31.08 MB/s
BenchmarkGet/256B-4         	 1000000	      5050 ns/op	  50.68 MB/s
BenchmarkGet/512B-4         	 2000000	      5284 ns/op	  96.88 MB/s
BenchmarkGet/1K-4           	 1000000	      5519 ns/op	 185.52 MB/s
BenchmarkGet/2K-4           	 1000000	      6860 ns/op	 298.52 MB/s
BenchmarkGet/4K-4           	 1000000	      8531 ns/op	 480.12 MB/s
BenchmarkGet/8K-4           	 1000000	     10902 ns/op	 751.41 MB/s
BenchmarkGet/16K-4          	  500000	     16330 ns/op	1003.25 MB/s
BenchmarkGet/32K-4          	  300000	     23638 ns/op	1386.22 MB/s
PASS
ok  	github.com/prologic/bitcask	81.157s
```

After:

```
$ go test -test.run -benchmem -benchtime=5s -bench=BenchmarkGet .
goos: darwin
goarch: amd64
pkg: github.com/prologic/bitcask
BenchmarkGet/128B-4         	 2000000	      5381 ns/op	  23.79 MB/s
BenchmarkGet/256B-4         	 1000000	      5812 ns/op	  44.04 MB/s
BenchmarkGet/512B-4         	 1000000	      6305 ns/op	  81.20 MB/s
BenchmarkGet/1K-4           	 1000000	      7055 ns/op	 145.13 MB/s
BenchmarkGet/2K-4           	 1000000	      9276 ns/op	 220.78 MB/s
BenchmarkGet/4K-4           	 1000000	     10166 ns/op	 402.90 MB/s
BenchmarkGet/8K-4           	  500000	     13265 ns/op	 617.53 MB/s
BenchmarkGet/16K-4          	  500000	     18760 ns/op	 873.32 MB/s
BenchmarkGet/32K-4          	  200000	     34164 ns/op	 959.12 MB/s
PASS
ok  	github.com/prologic/bitcask	78.310s
```

**Comment by prologic** [comment]
This brings read/write allocs down to 4/5 respectively:

```
goos: darwin
goarch: amd64
pkg: github.com/prologic/bitcask
BenchmarkGet/128B-4         	  300000	      4652 ns/op	  27.51 MB/s	     387 B/op	       4 allocs/op
BenchmarkGet/256B-4         	  300000	      5233 ns/op	  48.92 MB/s	     643 B/op	       4 allocs/op
BenchmarkGet/512B-4         	  300000	      5413 ns/op	  94.57 MB/s	    1187 B/op	       4 allocs/op
BenchmarkGet/1K-4           	  300000	      5710 ns/op	 179.32 MB/s	    2275 B/op	       4 allocs/op
BenchmarkGet/2K-4           	  200000	      7210 ns/op	 284.03 MB/s	    4451 B/op	       4 allocs/op
BenchmarkGet/4K-4           	  200000	      9145 ns/op	 447.86 MB/s	    9059 B/op	       4 allocs/op
BenchmarkGet/8K-4           	  100000	     11507 ns/op	 711.88 MB/s	   17763 B/op	       4 allocs/op
BenchmarkGet/16K-4          	  100000	     16660 ns/op	 983.41 MB/s	   34915 B/op	       4 allocs/op
BenchmarkGet/32K-4          	   50000	     31721 ns/op	1032.99 MB/s	   73827 B/op	       4 allocs/op
BenchmarkPut/128B-4         	  100000	     16184 ns/op	   7.91 MB/s	     401 B/op	       5 allocs/op
BenchmarkPut/256B-4         	  100000	     18480 ns/op	  13.85 MB/s	     531 B/op	       5 allocs/op
BenchmarkPut/512B-4         	  100000	     21722 ns/op	  23.57 MB/s	     821 B/op	       5 allocs/op
BenchmarkPut/1K-4           	   50000	     29838 ns/op	  34.32 MB/s	    1403 B/op	       5 allocs/op
BenchmarkPut/2K-4           	   30000	     46982 ns/op	  43.59 MB/s	    2566 B/op	       5 allocs/op
BenchmarkPut/4K-4           	   20000	     75766 ns/op	  54.06 MB/s	    5147 B/op	       5 allocs/op
BenchmarkPut/8K-4           	   10000	    130000 ns/op	  63.02 MB/s	    9805 B/op	       5 allocs/op
BenchmarkPut/16K-4          	   10000	    203176 ns/op	  80.64 MB/s	   18844 B/op	       5 allocs/op
BenchmarkPut/32K-4          	    5000	    356241 ns/op	  91.98 MB/s	   41541 B/op	       6 allocs/op
BenchmarkScan-4             	  500000	      2124 ns/op	     493 B/op	      25 allocs/op
PASS
ok  	github.com/prologic/bitcask	34.755s
```

**Comment by jsign** [comment]
Bucketing idea and results:
```
diff --git a/internal/datafile.go b/internal/datafile.go
index dfb2f27..d58565d 100644
--- a/internal/datafile.go
+++ b/internal/datafile.go
@@ -6,6 +6,7 @@ import (
        "path/filepath"
        "sync"
 
+       "github.com/oxtoacart/bpool"
        "github.com/pkg/errors"
        "golang.org/x/exp/mmap"
 
@@ -134,10 +135,18 @@ func (df *Datafile) Read() (e pb.Entry, n int64, err error) {
        return
 }
 
+var mapBufPool map[int64]*bpool.BytePool = make(map[int64]*bpool.BytePool)
+
 func (df *Datafile) ReadAt(index, size int64) (e pb.Entry, err error) {
        var n int
 
-       b := make([]byte, size)
+       pool := mapBufPool[size]
+       if pool == nil {
+               pool = bpool.NewBytePool(64, int(size))
+               mapBufPool[size] = pool
+       }
+
+       b := pool.Get()
 
        if df.w == nil {
                n, err = df.ra.ReadAt(b, index)
@@ -151,11 +160,11 @@ func (df *Datafile) ReadAt(index, size int64) (e pb.Entry, err error) {
                err = ErrReadError
                return
        }
-
        err = proto.Unmarshal(b[prefixSize:], &e)
        if err != nil {
                return
        }
+       pool.Put(b)
        return
 }
```
Before (last commit from this PR):
```
goos: linux
goarch: amd64
pkg: github.com/prologic/bitcask
BenchmarkGet/128B-8              1000000              1236 ns/op         103.53 MB/s         387 B/op          4 allocs/op
BenchmarkGet/256B-8              1000000              1386 ns/op         184.66 MB/s         643 B/op          4 allocs/op
BenchmarkGet/512B-8              1000000              1432 ns/op         357.47 MB/s        1187 B/op          4 allocs/op
BenchmarkGet/1K-8                1000000              1925 ns/op         531.75 MB/s        2275 B/op          4 allocs/op
BenchmarkGet/2K-8                 500000              2447 ns/op         836.72 MB/s        4451 B/op          4 allocs/op
BenchmarkGet/4K-8                 300000              3975 ns/op        1030.21 MB/s        9059 B/op          4 allocs/op
BenchmarkGet/8K-8                 200000              6327 ns/op        1294.73 MB/s       17763 B/op          4 allocs/op
BenchmarkGet/16K-8                200000             11027 ns/op        1485.80 MB/s       34915 B/op          4 allocs/op
BenchmarkGet/32K-8                100000             21149 ns/op        1549.36 MB/s       73827 B/op          4 allocs/op
```

After:
```
goos: linux
goarch: amd64
pkg: github.com/prologic/bitcask
BenchmarkGet/128B-8              1000000              1214 ns/op         105.37 MB/s         227 B/op          3 allocs/op
BenchmarkGet/256B-8              1000000              1243 ns/op         205.83 MB/s         355 B/op          3 allocs/op
BenchmarkGet/512B-8              1000000              1346 ns/op         380.30 MB/s         611 B/op          3 allocs/op
BenchmarkGet/1K-8                1000000              1575 ns/op         649.94 MB/s        1123 B/op          3 allocs/op
BenchmarkGet/2K-8                1000000              2050 ns/op         998.85 MB/s        2147 B/op          3 allocs/op
BenchmarkGet/4K-8                 500000              2897 ns/op        1413.80 MB/s        4195 B/op          3 allocs/op
BenchmarkGet/8K-8                 300000              4586 ns/op        1786.24 MB/s        8291 B/op          3 allocs/op
BenchmarkGet/16K-8                200000              7626 ns/op        2148.18 MB/s       16483 B/op          3 allocs/op
BenchmarkGet/32K-8                100000             14728 ns/op        2224.87 MB/s       32867 B/op          3 allocs/op
```

**Comment by prologic** [comment]
What's your conclusion of bucketing the buffer pool here?

**Comment by jsign** [comment]
Apart from saving the extra alloc, just the implementation idea.

At this point, I'd rather apply you original idea in a single pool but using https://github.com/oxtoacart/bpool/blob/master/bufferpool.go#L9. This would autoadjust sizes in worst cases.

The bucketing idea makes sense if there's some kind of eviction when some buckets aren't used for long time in order to release resources.

Maybe it's better to start with this single pool with the maxConcurrency config and let the future drive design.

**Comment by jsign** [comment]
I can finish this idea tomorrow if you like

**Comment by prologic** [comment]
Yup agreed; I think of all the things we've explored between us it probably makes sense to just keep it simple and configurable for now. buffer pools with configurable size using functional options -- maybe default ot the existing `master` beheaviour by default?

**Comment by prologic** [comment]
This is being superceded by #36

**Pull request closed without merging**
