### PR TITLE
new merge approach

### PR DESCRIPTION
**Pull request by yashschandra**

### CODE REVIEW

**Comment by yashschandra** [comment]
@prologic added a flag to allow only 1 merge at a time. Unfortunately writing test cases for that does not look straightforward 😞

**Comment by prologic** [comment]
Are the failing CI just bogus?

Also can you describe how you tested this or some steps that I can try to test this myself in the desc?

**Comment by yashschandra** [comment]
Tests are failing for windows only, not sure why though.

Found an issue stated [here](https://github.com/prologic/bitcask/issues/187#issuecomment-739501962), thinking of possible solutions.

**Comment by prologic** [comment]
Nice thanks! Keep poking me to get through these and merged :)

**Comment by yashschandra** [comment]
updated the _Get_ api and _Merge_  approach, now there should be no recursive locking. Though whilst _Merge_ is running, we are bound to get few errors in _Put_ (between **b.Close()** and **b.Reopen()** inside _Merge_ method). To solve this, we will need to refactor locking.

**Comment by yashschandra** [comment]
@prologic  Also I am not sure why test cases for windows keeps on failing, all tests pass on my pc (OSX)

**Comment by prologic** [comment]
> @prologic Also I am not sure why test cases for windows keeps on failing, all tests pass on my pc (OSX), do you happen to know why?

besides the fact that Windows sucks? No I don't 👍 
I'm considering dropping support for Windows entirely as there is very little interest in it and no-one that maintains this library has access to a Windows dev environment.

**Comment by yashschandra** [comment]
Did you get time to look at the pr?

**Comment by prologic** [comment]
not yet 😂 what production loads have you tested this with? No issues with the new approach ?

**Comment by yashschandra** [comment]
I did not explicitly run it on production but did the test to check whether I still get deadlock situation (I did not after the change)
```
func v4() {
	db, _ := bitcask.Open("/tmp/bitcask1", bitcask.WithMaxDatafileSize(1000))
	go func() {
		for {
			time.Sleep(100*time.Millisecond)
			i := rand.Intn(1000)
			k := fmt.Sprintf("k%03d", i)
			v := fmt.Sprintf("v%03d", i)
			err :=db.Put([]byte(k), []byte(v))
			fmt.Println(err)
		}
	}()
	go func() {
		for {
			time.Sleep(1*time.Second)
			err := db.Merge()
			fmt.Println(err)
		}
	}()
	go func() {
		for {
			time.Sleep(10*time.Millisecond)
			i := rand.Intn(1000)
			k := fmt.Sprintf("k%03d", i)
			val, err := db.Get([]byte(k))
			fmt.Println(val, err)
		}
	}()
	<-time.After(1*time.Minute)
}

func main() {
	v4()
}
```

It ran for a minute without any issues.

For correctness, I am relying on the test cases and some manual testing.

**Comment by prologic** [comment]
Very nice! I'll run this on some production like workloads over the weekend and test it more thoroughly then we'll merge 😎￼

**Comment by prologic** [comment]
Hmmm once of the benchmark tests is failing:

```#!sh
BenchmarkPut/8KNoSync
    bitcask_test.go:1759: open /Users/prologic/Projects/bitcask/bitcask_bench783558592/000000247.data: too many open files
--- FAIL: BenchmarkPut/8KNoSync-12
BenchmarkPut/16KNoSync
    bitcask_test.go:1759: sync /Users/prologic/Projects/bitcask/bitcask_bench783558592/000000246.data: file already closed
--- FAIL: BenchmarkPut/16KNoSync
BenchmarkPut/32KNoSync
    bitcask_test.go:1759: sync /Users/prologic/Projects/bitcask/bitcask_bench783558592/000000246.data: file already closed
--- FAIL: BenchmarkPut/32KNoSync
    bitcask_test.go:1745: open /Users/prologic/Projects/bitcask/bitcask_bench534510623/000000000.data: too many open files
--- FAIL: BenchmarkPut
BenchmarkScan
BenchmarkScan-12             	  605541	      1744 ns/op	     392 B/op	      33 allocs/op
FAIL
exit status 1
FAIL	github.com/prologic/bitcask	26.796s
FAIL
make: *** [bench] Error 1
```

Are we leaking an open file somewhere?

**Comment by prologic** [comment]
Oh this happens on mster too 😢 That's a bug that needs fixing :/

**Comment by yashschandra** [comment]
> updated the Get api and Merge approach, now there should be no recursive locking. **Though while Merge is running, we are bound to get few errors in Put (between b.Close() and b.Reopen() inside Merge method). To solve this, we will need to refactor locking.**

This is actually a limitation in merge.

**Pull request merged**
