### PR TITLE
Use a Radix Tree for prefix scans

### LINKED ISSUE #67: Very high RAM usage
My app is intending to write a total of around 3.6 GiB to the database. Keys are all 32 bytes long and values are all around 4 KiB.

```
[i] Encrypting 9 files from "test_data" (3.596GiB)
[?] Enter master key: ;
[i] Processing key...
[+] Sealing test_data/1k.data (1KiB)
[+] Sealing test_data/2m.data (2MiB)
[+] Sealing test_data/4k.data (4KiB)
[+] Sealing test_data/checksum.json (450B)
[+] Sealing test_data/folder/32m.data (32MiB)
[+] Sealing test_data/folder/64m.data (64MiB)
[+] Sealing test_data/folder/large/1g.data (1GiB)
[+] Sealing test_data/folder/large/2g.data (2GiB)
[+] Sealing test_data/folder/large/512m.data (512MiB)
[i] Syncing data with disk...
[i] Compacting database...
[1]    18243 killed     ./gravity seal test_data
```

That last line there where the process is killed during the `Merge` operation is due to the application using around 13 GB of RAM and being killed by the operating system. Before the merge operation, memory usage peaked at around 7-8 GB.

### PR DESCRIPTION
**Pull request by prologic**
An alternative implementation or Prefix Scan that hopefully addresses #67 by using a compact trie (_also known as a Radix Tree_) where redundant nodes are removed. See [Radix Tree](https://en.wikipedia.org/wiki/Radix_tree)

Fixes #67 (_hopefully_)

@awnumar Are you able to test this branch?

### CODE REVIEW

**Comment by prologic** [comment]
Running @jsign 's original test program in #67 produces this heap profile:

profile001

**Comment by prologic** [comment]
Performance compared to master is negible:

```
$ go test -run none -bench=BenchmarkScan -benchmem -count 5
goos: darwin
goarch: amd64
pkg: github.com/prologic/bitcask
BenchmarkScan-4   	  200000	      6271 ns/op	     390 B/op	      29 allocs/op
BenchmarkScan-4   	  200000	      6081 ns/op	     390 B/op	      29 allocs/op
BenchmarkScan-4   	  200000	      6107 ns/op	     390 B/op	      29 allocs/op
BenchmarkScan-4   	  200000	      7045 ns/op	     390 B/op	      29 allocs/op
BenchmarkScan-4   	  200000	      7669 ns/op	     390 B/op	      29 allocs/op
PASS
ok  	github.com/prologic/bitcask	7.183s
```

**Comment by prologic** [comment]
The real question will be whether there is a significant reduction in memory footprint for cases like @awnumar 's

**Comment by awnumar** [comment]
Greedy scan enabled:
```
Showing nodes accounting for 238.70MB, 99.79% of 239.21MB total
Dropped 31 nodes (cum <= 1.20MB)
Showing top 10 nodes out of 27
      flat  flat%   sum%        cum   cum%
   76.85MB 32.13% 32.13%    76.85MB 32.13%  github.com/prologic/bitcask/internal.(*Keydir).Add
   73.47MB 30.71% 62.84%    90.26MB 37.73%  github.com/prologic/bitcask/internal.(*RadixTree).Add
   24.62MB 10.29% 73.13%    24.62MB 10.29%  golang.org/x/crypto/nacl/secretbox.sliceForAppend
   22.52MB  9.41% 82.54%    22.52MB  9.41%  main.(*Identifier).Derive
   17.09MB  7.14% 89.69%    22.91MB  9.58%  reflect.Value.MapKeys
   16.61MB  6.94% 96.63%    16.80MB  7.02%  github.com/prologic/bitcask/internal.(*node).addEdge
    5.96MB  2.49% 99.12%     5.96MB  2.49%  reflect.copyVal
    1.37MB  0.57% 99.69%     1.37MB  0.57%  encoding/gob.(*encBuffer).Write
    0.22MB 0.092% 99.79%    24.84MB 10.38%  main.encrypt
         0     0% 99.79%    24.43MB 10.21%  encoding/gob.(*Encoder).Encode
```
Greedy scan disabled:
```
Showing nodes accounting for 156.53MB, 99.85% of 156.76MB total
Dropped 16 nodes (cum <= 0.78MB)
Showing top 10 nodes out of 25
      flat  flat%   sum%        cum   cum%
   76.54MB 48.83% 48.83%    76.54MB 48.83%  github.com/prologic/bitcask/internal.(*Keydir).Add
   23.29MB 14.85% 63.68%    23.29MB 14.85%  main.(*Identifier).Derive
   17.09MB 10.90% 74.58%    22.86MB 14.58%  reflect.Value.MapKeys
   16.95MB 10.81% 85.39%    16.95MB 10.81%  encoding/gob.(*encBuffer).Write
   13.55MB  8.65% 94.03%    13.55MB  8.65%  encoding/gob.(*encBuffer).WriteByte
    9.12MB  5.82% 99.85%     9.12MB  5.82%  reflect.copyVal
         0     0% 99.85%    56.71MB 36.17%  encoding/gob.(*Encoder).Encode
         0     0% 99.85%    56.71MB 36.17%  encoding/gob.(*Encoder).EncodeValue
         0     0% 99.85%    56.71MB 36.17%  encoding/gob.(*Encoder).encode
         0     0% 99.85%    56.71MB 36.17%  encoding/gob.(*Encoder).encodeMap
```

**Comment by awnumar** [comment]
**Re-running with larger data-set (~4GB) and merge enabled.**

Greedy scan enabled:
profile003

Greedy scan disabled:
profile002

Interestingly `System Monitor` reports higher memory usage (2.1 GB for greedy scan enabled). Not sure the reason for the discrepancy.

**Comment by prologic** [comment]
> Interestingly System Monitor reports higher memory usage (2.1 GB for greedy scan enabled). Not sure the reason for the discrepancy.

Can you show the RSS, Virtual and Shared/Cached memory of the process?

Looking at your two results; This looks much better to me? We're only holding as much data as the keydir itself in the radix tree.

**Comment by prologic** [comment]
In the original report in #67 you were showing ~2.1GB of memory used by the old `trie.NewChild()` method:

**Comment by prologic** [comment]
@awnumar So is this implementation better or worse than master? Better/Worse than the custom trie (new_trie branch)?

There is on e more implementation that can improve this again and that is to use an Adaptive Radix Tree -- or ART which I may put up later on in the week for comparision.

**Comment by awnumar** [comment]
It's better.

**Comment by prologic** [comment]
Is it enough for you to _not_ disable fast prefix scans in your case?

**Comment by awnumar** [comment]
> Is it enough for you to not disable fast prefix scans in your case?

Unfortunately not as the memory usage is still 80% higher, which is manageable so far but the only thing that would prompt me to disable the Scan optimizations (given that I don't use them) is if the overhead was negligible.

**Comment by prologic** [comment]
Superseded by #71 which is more comptact again by using adaptive structures and performs better.

**Pull request closed without merging**
