### PR TITLE
Use an Adaptive Radix Tree

### LINKED ISSUE #67: Very high RAM usage
My app is intending to write a total of around 3.6 GiB to the database. Keys are all 32 bytes long and values are all around 4 KiB.

```
[i] Encrypting 9 files from "test_data" (3.596GiB)
[?] Enter master key: ;
[i] Processing key...
[+] Sealing test_data/1k.data (1KiB)
[+] Sealing test_data/2m.data (2MiB)
[+] Sealing test_data/4k.data (4KiB)
[+] Sealing test_data/checksum.json (450B)
[+] Sealing test_data/folder/32m.data (32MiB)
[+] Sealing test_data/folder/64m.data (64MiB)
[+] Sealing test_data/folder/large/1g.data (1GiB)
[+] Sealing test_data/folder/large/2g.data (2GiB)
[+] Sealing test_data/folder/large/512m.data (512MiB)
[i] Syncing data with disk...
[i] Compacting database...
[1]    18243 killed     ./gravity seal test_data
```

That last line there where the process is killed during the `Merge` operation is due to the application using around 13 GB of RAM and being killed by the operating system. Before the merge operation, memory usage peaked at around 7-8 GB.

### PR DESCRIPTION
**Pull request by prologic**
An alternative implementation or Prefix Scan that hopefully addresses #67 by using a Adaptive Radix Tree which is similar to a Radix Tree (_compact trie_) but uses some clever techniques to reduce memory footprint and wasted node pointers. See [the paper](https://db.in.tum.de/~leis/papers/ART.pdf) and this [nice article](https://www.the-paper-trail.org/post/art-paper-notes/) that does a good job of explaining the concepts for the non-academics :)

Similar to #70 

Fixes #67 (_hopefully_)

@awnumar I'd love it if you could compare this implementation and compare with #70 -- If you have time a comparison of master, use_radix and use_adapative_radix_tree would be awesome!

### CODE REVIEW

**Comment by prologic** [comment]
profile002

**Comment by awnumar** [comment]
Greedy scan enabled, this branch, 4GB data-set. `RES` peaked at 5.8g, shr at 3.9g.

```
(pprof) top
Showing nodes accounting for 945.62MB, 99.05% of 954.68MB total
Dropped 48 nodes (cum <= 4.77MB)
Showing top 10 nodes out of 42
      flat  flat%   sum%        cum   cum%
  289.08MB 30.28% 30.28%   289.08MB 30.28%  github.com/prologic/bitcask/internal.(*Keydir).Add
  183.99MB 19.27% 49.55%   183.99MB 19.27%  github.com/plar/go-adaptive-radix-tree.(*objFactory).newLeaf
  179.12MB 18.76% 68.32%   179.12MB 18.76%  encoding/gob.(*encBuffer).Write
   60.77MB  6.37% 74.68%   602.66MB 63.13%  github.com/prologic/bitcask.(*Bitcask).Put
   55.42MB  5.81% 80.49%    55.42MB  5.81%  reflect.copyVal
   46.17MB  4.84% 85.32%    61.59MB  6.45%  reflect.Value.MapKeys
   42.39MB  4.44% 89.76%    42.39MB  4.44%  github.com/plar/go-adaptive-radix-tree.(*objFactory).newNode48
   40.39MB  4.23% 93.99%    40.39MB  4.23%  bytes.makeSlice
   30.89MB  3.24% 97.23%    30.89MB  3.24%  main.(*Identifier).Derive
   17.39MB  1.82% 99.05%    17.39MB  1.82%  github.com/plar/go-adaptive-radix-tree.(*objFactory).newNode16
```

profile001

**Comment by awnumar** [comment]
With it disabled it was 4.7g/3.9g respectively.

```
Showing nodes accounting for 432.79MB, 99.88% of 433.33MB total
Dropped 45 nodes (cum <= 2.17MB)
Showing top 10 nodes out of 27
      flat  flat%   sum%        cum   cum%
  186.37MB 43.01% 43.01%   186.37MB 43.01%  reflect.mapassign
  144.54MB 33.36% 76.36%   144.54MB 33.36%  github.com/prologic/bitcask/internal.(*Keydir).Add
   40.39MB  9.32% 85.69%    40.39MB  9.32%  encoding/gob.(*decBuffer).Size
   30.94MB  7.14% 92.82%    30.94MB  7.14%  reflect.unsafe_NewArray
   30.56MB  7.05% 99.88%    30.56MB  7.05%  main.(*Identifier).Derive
         0     0% 99.88%   257.71MB 59.47%  encoding/gob.(*Decoder).Decode
         0     0% 99.88%   257.71MB 59.47%  encoding/gob.(*Decoder).DecodeValue
         0     0% 99.88%   217.30MB 50.15%  encoding/gob.(*Decoder).decOpFor.func2
         0     0% 99.88%   217.30MB 50.15%  encoding/gob.(*Decoder).decodeMap
         0     0% 99.88%   217.30MB 50.15%  encoding/gob.(*Decoder).decodeSingle
```

**Comment by prologic** [comment]
WOW! So to summarize:

That's pretty awesome! I did some more playing around and it _looks_ like the performance of key lookups (_we're just looking up their file id, offset and size_) is just as fast with this Adapative Radix Tree than it is using a hash map. Therefore I _think_ if we refactor out the keydir to just ust an ART we'll have the best of both. What do you think?

At

**Comment by prologic** [comment]
I'd also like to get rid of all this reflect memory being used too :/ This must be coming from merges and indexes getting written using `gob`. Not sure why they don't get garbage collected?

**Comment by prologic** [comment]
Amazingly the ART uses less memory to hold your entire key space than the hash table keydir does

**Comment by jsign** [comment]
Oh, I missed this. Makes a lot of sense, it's a great change.

**Comment by prologic** [comment]
Yes ! :) If we replace the keydir with this I _think_ we can get the best of both worlds without consuming the world of memory!

**Pull request merged**
