### PR TITLE
Fix a bug wit the decoder passing the wrong value for the value's offset into the buffer

### LINKED ISSUE #76: Deleting keys appears btoken
On master with this diff applied:

```#!diff
diff --git a/bitcask.go b/bitcask.go
index c923f32..b515405 100644
--- a/bitcask.go
+++ b/bitcask.go
@@ -4,6 +4,7 @@ import (
 	"bytes"
 	"encoding/json"
 	"errors"
+	"fmt"
 	"hash/crc32"
 	"io"
 	"io/ioutil"
@@ -13,8 +14,7 @@ import (
 	"sync"
 
 	"github.com/gofrs/flock"
-	"github.com/plar/go-adaptive-radix-tree"
-
+	art "github.com/plar/go-adaptive-radix-tree"
 	"github.com/prologic/bitcask/internal"
 )
 
@@ -89,9 +89,11 @@ func (b *Bitcask) Close() error {
 		os.Remove(b.Flock.Path())
 	}()
 
-	if err := b.keydir.Save(path.Join(b.path, "index")); err != nil {
-		return err
-	}
+	/*
+		if err := b.keydir.Save(path.Join(b.path, "index")); err != nil {
+			return err
+		}
+	*/
 
 	for _, df := range b.datafiles {
 		if err := df.Close(); err != nil {
@@ -174,7 +176,7 @@ func (b *Bitcask) Put(key, value []byte) error {
 // Delete deletes the named key. If the key doesn't exist or an I/O error
 // occurs the error is returned.
 func (b *Bitcask) Delete(key []byte) error {
-	_, _, err := b.put(key, []byte{})
+	_, _, err := b.put(key, nil)
 	if err != nil {
 		return err
 	}
@@ -322,17 +324,20 @@ func (b *Bitcask) reopen() error {
 	}
 
 	if internal.Exists(path.Join(b.path, "index")) {
-		if err := keydir.Load(path.Join(b.path, "index")); err != nil {
-			return err
-		}
-		for key := range keydir.Keys() {
-			item, _ := keydir.Get(key)
-			if b.config.greedyScan {
-				t.Insert(key, item)
+		/*
+			if err := keydir.Load(path.Join(b.path, "index")); err != nil {
+				return err
 			}
-		}
+			for key := range keydir.Keys() {
+				item, _ := keydir.Get(key)
+				if b.config.greedyScan {
+					t.Insert(key, item)
+				}
+			}
+		*/
 	} else {
 		for i, df := range datafiles {
+			fmt.Printf("Reading df %d\n", i)
 			for {
 				e, n, err := df.Read()
 				if err != nil {
@@ -342,8 +347,10 @@ func (b *Bitcask) reopen() error {
 					return err
 				}
 
+				fmt.Printf("%#v\n", e)
+
 				// Tombstone value  (deleted key)
-				if len(e.Value) == 0 {
+				if e.Value == nil {
 					keydir.Delete(e.Key)
 					continue
 				}
```

Skipping the index (keydir) persistence; deleting keys doesn't appear to work correctly:

```
james@Jamess-MacBook-Pro
Fri Aug 30 12:21:29
~/Contributions/bitcask
 (master) 0
$ ./bitcask -p ./tmp.db keys

james@Jamess-MacBook-Pro
Fri Aug 30 12:21:36
~/Contributions/bitcask
 (master) 0
$ ./bitcask -p ./tmp.db set foo bar
Reading df 0

james@Jamess-MacBook-Pro
Fri Aug 30 12:21:39
~/Contributions/bitcask
 (master) 0
$ ./bitcask -p ./tmp.db get foo
Reading df 0
internal.Entry{Checksum:0x76ff8caa, Key:[]uint8{0x66, 0x6f, 0x6f}, Offset:0, Value:[]uint8{0x62, 0x61, 0x72}}
bar

james@Jamess-MacBook-Pro
Fri Aug 30 12:21:43
~/Contributions/bitcask
 (master) 0
$ ./bitcask -p ./tmp.db keys
Reading df 0
internal.Entry{Checksum:0x76ff8caa, Key:[]uint8{0x66, 0x6f, 0x6f}, Offset:0, Value:[]uint8{0x62, 0x61, 0x72}}
foo

james@Jamess-MacBook-Pro
Fri Aug 30 12:21:46
~/Contributions/bitcask
 (master) 0
$ ./bitcask -p ./tmp.db delete foo
Reading df 0
internal.Entry{Checksum:0x76ff8caa, Key:[]uint8{0x66, 0x6f, 0x6f}, Offset:0, Value:[]uint8{0x62, 0x61, 0x72}}

james@Jamess-MacBook-Pro
Fri Aug 30 12:21:52
~/Contributions/bitcask
 (master) 0
$ ./bitcask -p ./tmp.db keys
Reading df 0
internal.Entry{Checksum:0x76ff8caa, Key:[]uint8{0x66, 0x6f, 0x6f}, Offset:0, Value:[]uint8{0x62, 0x61, 0x72}}
internal.Entry{Checksum:0x0, Key:[]uint8{}, Offset:0, Value:[]uint8{0x66, 0x6f, 0x6f}}
foo


james@Jamess-MacBook-Pro
Fri Aug 30 12:21:54
~/Contributions/bitcask
 (master) 0
$ ./bitcask -p ./tmp.db get foo
Reading df 0
internal.Entry{Checksum:0x76ff8caa, Key:[]uint8{0x66, 0x6f, 0x6f}, Offset:0, Value:[]uint8{0x62, 0x61, 0x72}}
internal.Entry{Checksum:0x0, Key:[]uint8{}, Offset:0, Value:[]uint8{0x66, 0x6f, 0x6f}}
bar

```

### PR DESCRIPTION
**Pull request by prologic**
Fixes #76 

/cc @jsign

### CODE REVIEW

**Comment by jsign** [comment]
Ups yes seems to be a good fix. I'd also change the name of the `DecodeWithoutPrefix` parameter to `keyOffset`.

**Comment by prologic** [comment]
Isn't it still called the `valueOffset` though? :) The way I think about it is this;

- `0` is the key offset
- `0 + actualKeySize` is the value offset
- ... etc ...

**Comment by jsign** [comment]
That's right... I should have said `keySize` instead of `keyOffset`. But better the way it is since changing to this option would mean coupling parameter names with the current design (maybe tomorrow before the value there's another field, who knows).

**Comment by prologic** [comment]
I'll merge if you review/approve :)

**Pull request merged**
