### PR TITLE
Test for data corruption in datafile decoding

### PR DESCRIPTION
**Pull request by jsign**
Continues #78 

Mostly reasonable refactors and tests, but I'll like to mention a particular thing.

In function `getKeyValueSizes()`, not only read value and key sizes are within upper bounds with configuration, but also key sizes should be greater than zero. For value size isn't the case because of tombstones (!).

This PR isn't quite finished yet because there's an extra test to be made. 
I'll tell when finished for review.

### CODE REVIEW

**Comment by jsign** [comment]
Yeah, 3 levels deep feel weird maybe. Can be moved to the same as `internal` level to keep it flat. Having it under `data` somehow gives the hint that that codec is for data... but that maybe sounds like forcing its scope (it just a codec, so let others decide how to use it)

I want to comment something about this last commit:
- I deleted the `translateError` function and its usage. I'm not sure what was its original intention, but it did something quite weird. Just deleting it didn't break any existing test, which seems nice. For an extra check, I took a look and the translated error transformation never was used by callers, so seems ok. Opinion?
- The test new test is quite verbose and tries no to assume the current implementation. Currently, only one of the test sub-cases is enough to test the intended case (since `ReadFull` reads the key, value and checksum data all at once, but anyway).

If this final review makes sense, it could be merged.

**Comment by prologic** [comment]
`translateError()` came from an older implementaiton of the datafile codec -- streampb. It probably should have been removed then but we missed it :)

**Comment by prologic** [comment]
Yeah I'm in two minds about the extra sub-package level; but its honestly not a blocker for me. Merge away if you're happy!

**Comment by prologic** [comment]
Only final comment I have is perhaps make use of the `testify/assert` package for making test assertions? I've grown a certain level of affinity of this package for writing tests and it produces nice verbose output and nice output when things go wrong. But up to you :)

**Comment by jsign** [comment]
It saves some lines, avoids necessarily thinking about a message, and makes the codebase more coherent in error checking... the second is good enough :)

**Comment by prologic** [comment]
> and makes the codebase more coherent in error checking

This is primarily why I like using `testify/assert` too :)

**Pull request merged**
