### PR TITLE
Improves Merge() operation by also pruning old key/value pairs

### LINKED ISSUE #27: Old duplicate keys are not pruned across rotated Datafiles
```
        --- PASS: TestMergeOpen/Setup/Close (0.02s)
    bitcask_test.go:353:
        	Error Trace:	bitcask_test.go:353
        	Error:      	Should be true
        	Test:       	TestMergeOpen
    --- PASS: TestMergeOpen/Merge (17.77s)
        --- PASS: TestMergeOpen/Merge/Merge (8.80s)
        --- PASS: TestMergeOpen/Merge/Open (8.95s)
        --- PASS: TestMergeOpen/Merge/Get (0.00s)
        --- PASS: TestMergeOpen/Merge/Close (0.02s)
FAIL
FAIL	github.com/prologic/bitcask	40.020s
```

### PR DESCRIPTION
**Pull request by prologic**
This is an improved version to address #27 

If the implementation is proven okay...

Fixes #27

There are some things still left to do before merging:

- [ ] Improve the unit tests for merging
- [x] Write unit tests for `.Stats()`
- [x] Fix missing Hintfiles

### CODE REVIEW

**Comment by prologic** [comment]
Before/After:

```#!sh
prologic@Jamess-MacBook
Fri Jul 26 14:46:39
~/Projects/bitcask
 (fix_broken_merge) 130
$ bitcask -p ./tmp.db/ stats
{
  "Datafiles": 1,
  "Keys": 11,
  "Size": 25529
}

prologic@Jamess-MacBook
Fri Jul 26 14:46:46
~/Projects/bitcask
 (fix_broken_merge) 0
$ du -b -h ./tmp.db
26K	./tmp.db

prologic@Jamess-MacBook
Fri Jul 26 14:46:52
~/Projects/bitcask
 (fix_broken_merge) 0
$ bitcask -p ./tmp.db/ merge

prologic@Jamess-MacBook
Fri Jul 26 14:47:00
~/Projects/bitcask
 (fix_broken_merge) 0
$ bitcask -p ./tmp.db/ stats
{
  "Datafiles": 1,
  "Keys": 11,
  "Size": 590
}

prologic@Jamess-MacBook
Fri Jul 26 14:47:09
~/Projects/bitcask
 (fix_broken_merge) 0
$ du -b -h ./tmp.db
686	./tmp.db
```

**Comment by prologic** [comment]
Couple of things to note about this version:

- Deprecated the `Merge()` function in favour of a method `.Merge()` on an open database
- Instead of merging and pruning we just rewrite the database.
- `Merge()` is no longer called on `Open()`
- The database is locked whilst it is undergoing a merge / compaction / rewrite

**Comment by prologic** [comment]
I can't understand why `TestLocking` now fails :/

**Comment by prologic** [comment]
> I can't understand why `TestLocking` now fails :/

Nevermind fixed that :)

**Comment by prologic** [comment]
Added some todos/tasks in the desc above.

One thing to note here is the code change has meant we've lost `.hint` files. The `Merge()` function used to generate these as key/values were compacted and tombstone values deleted.
This doesn't seem possible to do now since we basically open a new "merge" db and just rewrite the current database into the "merge" db reusing all of the same behaviour. -- You get collapsed rotated files too if enough keys get deleted over time across data files.

We need to probably figure out a way to bring back the Hintfiles though or something equivalent or startup times will be affected on large datasets.

**Comment by prologic** [comment]
Added some todos/tasks in the desc above.

One thing to note here is the code change has meant we've lost `.hint` files. The `Merge()` function used to generate these as key/values were compacted and tombstone values deleted.
This doesn't seem possible to do now since we basically open a new "merge" db and just rewrite the current database into the "merge" db reusing all of the same behaviour. -- You get collapsed rotated files too if enough keys get deleted over time across data files.

We need to probably figure out a way to bring back the Hintfiles though or something equivalent or startup times will be affected on large datasets.

**Comment by awnumar** [comment]
Nice work. I have work at the moment and I'm juggling a few projects at the same time but I'll try to take a proper look at this on the weekend.

> One thing to note here is the code change has meant we've lost .hint files.

Hint files are for startup right? So what I would do is call Merge/Prune/whatever and then call Close. One of these should generate the hint files, maybe Close since it is called on every single close. You could even put the merge call inside close although you don't want it called twice so there could be a check to see if it has already been called, although this might be more effort than it's worth.

**Comment by prologic** [comment]
Haha that's precisely what I did just now ;)

It only supports a single "index" at the moment but it should only ever grow to the size of your key space itself -- Same for your memory usage. You are limited by memory and your keyspace size.

**Comment by prologic** [comment]
I'm going to merge this since it is an improvement after-all tests pass and it does what we discussed. When you get a chance to battle test it with your larger dataset that would be awesome!

**Pull request merged**
