### PR TITLE
Debugging panic while migration to v1

### PR DESCRIPTION
**Pull request by yashschandra**
Added logs to get more information for debugging. Could be a victim of thing mentioned [here](https://github.com/golang/go/issues/38673)

### CODE REVIEW

**Comment by yashschandra** [comment]
@prologic can you run same export command in this branch? I want to check key and value sizes

**Comment by prologic** [comment]
I can't repro this anymore.

I ran an instance of [jointwt/twtxt](https://github.com/jointwt/twtxt) with an old version of Bitcask, then updated to new version, database got upgraded and then checked out this branch. Everything works.

**Review by prologic — APPROVED** [review]

**Comment by yashschandra** [comment]
Well then we don't need this pr anymore 😄 , closing it

**Comment by prologic** [comment]
If I see it again I'll ping you !

**Pull request closed without merging**
