### PR TITLE
local live backup support

### PR DESCRIPTION
**Pull request by yashschandra**

### CODE REVIEW

**Comment by yashschandra** [comment]
@prologic pr for issue #171

**Comment by prologic** [comment]
Oh very nice 😁 Giving me too much work 🤣

**Comment by prologic** [comment]
Looks reasonable

**Comment by yashschandra** [comment]
> Oh very nice 😁 Giving me too much work 🤣

Haha... didn't mean to overwhelm you 😃 , just found this project interesting. I am also looking into bitraft so except some discussions on that repo too... 😛

**Comment by prologic** [comment]
Yeah I'd like to sit down one day and rewrite Bitraft to not be a toy

**Comment by yashschandra** [comment]
> Oh very nice 😁 Giving me too much work 🤣

is it that much work? 😛

**Review by prologic — APPROVED** [review]

**Pull request merged**
