### PR TITLE
Adds new API Stats() and Prune()

### LINKED ISSUE #27: Old duplicate keys are not pruned across rotated Datafiles
```
        --- PASS: TestMergeOpen/Setup/Close (0.02s)
    bitcask_test.go:353:
        	Error Trace:	bitcask_test.go:353
        	Error:      	Should be true
        	Test:       	TestMergeOpen
    --- PASS: TestMergeOpen/Merge (17.77s)
        --- PASS: TestMergeOpen/Merge/Merge (8.80s)
        --- PASS: TestMergeOpen/Merge/Open (8.95s)
        --- PASS: TestMergeOpen/Merge/Get (0.00s)
        --- PASS: TestMergeOpen/Merge/Close (0.02s)
FAIL
FAIL	github.com/prologic/bitcask	40.020s
```

### PR DESCRIPTION
**Pull request by prologic**
Fixes #27

At least partially. THe problem that was observed here was originally that
`Merge()` was _thought_ to reclaim disk space. It does sort of; but it was
implemented to only collapse duplicate keys written and tombstone values in
old rotated datafiles but not prune duplicated keys written across rotated
datafiles.

Let's try to explain this another way... Say you had a maximum datafile size of
1KB. You write keys `a` and `b` each with 512B values. You then update `a` with
another 512B value overriding the previous key/value pair. Meanwhile you've
reached the maximum datafile size so the active datafile gets rotated out
but now you have two versions of `a`, one in an older datafile and one in a
newer one. The `Merge()` operation didn't handle this.

The question now becomes; Do we merge the `Merge()` and `Prune()` operations
together?

### CODE REVIEW

**Comment by awnumar** [comment]
I'll test this soon.

> The question now becomes; Do we merge the Merge() and Prune() operations
together?

I would be in favor of this as there's probably no point in keeping them separate. (Who would want the first functionality without the second?)

A question: if I have ten data files and after merge/prune all the data can fit inside four of them, will there be four files in the store directory or ten still?

**Comment by prologic** [comment]
> A question: if I have ten data files and after merge/prune all the data can fit inside four of them, will there be four files in the store directory or ten still?

There will still be 10. This is a rather tricky problem because AFACT this goes against the design of the original paper in where once a Hintfile was written the associated Datafiles were considered "merged".

Introducing pruning however means we laways have to go back over old Dataifles (_in reverse_) and prune old key/value pairs.

I agree with you though; who would want `Merge()` without `Prune()` -- seems suboptimal to have a database that doesn't have a full prune, compact and merge operation.

**Comment by prologic** [comment]
Combining `Merge()` and `Prune()` together would invalidate the need for `.hint` files. We would always be rewriting all the datafiles.

There is one way I can think  of to partially preserve some of the existing design. That is to combine `Merge() and `Prune()` into a single API / function; But not to call this on `Open()` -- Allowing the database to utilise `.hint` files written at the end of `Prune+Merge()`.

The Hintfiles were part of the original paper's design I believe to help boost startup performance -- Something we should keep if we can?

**Comment by awnumar** [comment]
> There is one way I can think of to partially preserve some of the existing design. That is to combine Merge() and Prune()into a single API / function; But not to call this onOpen()-- Allowing the database to utilise.hintfiles written at the end ofPrune+Merge()`.

That makes sense to me.

I have just tested this and it does indeed compact the database down, although there is around half a dozen extra MB after the compaction than before any duplicates were added. This can be explained though by all the extra files that hang around.

```
...
-rw-r----- 1 awn awn 1.1M Jul 25 22:58 000000396.data
-rw-r--r-- 1 awn awn  20K Jul 25 22:58 000000396.hint
-rw-r----- 1 awn awn 1.1M Jul 25 22:58 000000397.data
-rw-r--r-- 1 awn awn  20K Jul 25 22:58 000000397.hint
-rw-r----- 1 awn awn 1.1M Jul 25 22:58 000000398.data
-rw-r--r-- 1 awn awn  20K Jul 25 22:58 000000398.hint
-rw-r----- 1 awn awn 1.1M Jul 25 22:58 000000399.data
-rw-r--r-- 1 awn awn  20K Jul 25 22:58 000000399.hint
-rw-r----- 1 awn awn 1.1M Jul 25 22:58 000000400.data
-rw-r--r-- 1 awn awn  20K Jul 25 22:58 000000400.hint
-rw-r----- 1 awn awn 1.1M Jul 25 22:58 000000401.data
-rw-r--r-- 1 awn awn  20K Jul 25 22:58 000000401.hint
-rw-r----- 1 awn awn 1.1M Jul 25 22:58 000000402.data
-rw-r--r-- 1 awn awn  20K Jul 25 22:58 000000402.hint
-rw-r----- 1 awn awn 236K Jul 25 22:58 000000403.data
```

**Comment by prologic** [comment]
Oh well that's good :D Improvement! I'm considering this issue a disk space optimization more than anything now. It was thankfully never a bug :)

So... I have to get to work shortly; But I would be thrilled if you took my code so far and expanded it to what we talked about? It definately needs some unit tests too! (_coverage has dropped in #28_)

One thing you'll notice is that in `Prune()` I walk backwards across the datafiles (_ignoring the active datafile_). THis is important and different to `Merge()` -- but I think if they were combined than you'd just use the logic of `Prune()` to achieve both behaviors.

**Comment by prologic** [comment]
And of course if you want to rename all datafiles after you're done.

**Comment by prologic** [comment]
But there's another approach I _think_ that could be even more space optimised.

Iterate over all datafiles in reverse ecept the active datafile.
Just write out new datafiles with a new incremental index adhering to the max datafile size.
Create `.hint` files as you go.
Remove all existing datafiles and rename the newly written ones.

PRoblem is what do you do with the active datafile whoose index will be slightly off?
One solution would be to not use an index for the active datafile -- But this could be more of an impact on the code change maybe. NOt sure :)

**Comment by prologic** [comment]
Probably worth dropping this in favor of #29

**Pull request closed without merging**
